http://localhost:8080/webapi/ordenador

######



GET http://localhost:8080/webapi/ordenador?inicio=1&items=5

###
GET http://localhost:8080/webapi/ordenador
######


GET http://localhost:8080/webapi/ordenador?modelo=HP
######

GET http://localhost:8080/webapi/ordenador?marca=Mars G

######

POST http://localhost:8080/webapi/ordenador
content-type: application/json

{
    "modelo": "Gaming Forcex",
    "marca": "Trinity",
    "precio": "1329.95",
    "numserie":"GX-47520Y" 
}
######

DELETE http://localhost:8080/webapi/ordenador/numserie/GT-75925T
######

GET http://localhost:8080/webapi/ordenador?inicio=1?items=5

######
